"""add rating

Revision ID: 33608a571358
Revises: 99b913310f8d
Create Date: 2024-06-13 11:36:23.267534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33608a571358'
down_revision = '99b913310f8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rating_sum', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('rating_num', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating_num')
        batch_op.drop_column('rating_sum')

    # ### end Alembic commands ###
